# This is a basic workflow to help you get started with Actions

name: Publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Publish Logseq
        uses: pengx17/logseq-publish@v0.1
        with:
          dest: docs
      - name: Remove U+2029 from published Logseq graph for GitHub Pages
        run: |
          cd docs
          wget -O logseq-publish-github-pages-wa.js https://gist.githubusercontent.com/gsongsong/b41dec1b348edc9e0fdfd60d43065d91/raw/edff588d4b75fa7aa04ab2048e5c1bc243a53e4b/logseq-publish-github-pages-wa.js
          node logseq-publish-github-pages-wa.js
      - name: Configure custom domain
        run: echo "telecom.jeon.engineer" > $GITHUB_WORKSPACE/docs/CNAME
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.9
        with:
          branch: gh-pages
          folder: docs
          clean: true
